services:
    haproxy:
        build: 'haproxy'
        ports:
            - 5432:5432
            - 7000:7000
        depends_on:
            - zoo1
            - pg-master
            - pg-slave

    zoo1:
        image: confluentinc/cp-zookeeper:latest
        container_name: zoo
        restart: always
        hostname: zoo1
        ports:
            - "2181:2181"
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000

    pg-master:
        build: 'postgres'
        container_name: pg-master
        restart: always
        hostname: pg-master
        environment:
            POSTGRES_USER: alfresco
            POSTGRES_PASSWORD: alfresco
            POSTGRES_DB: alfresco
            PGDATA: '/var/lib/postgresql/data/pgdata'
        expose:
            - 5432
            - 8008
        ports:
            - 5433:5432
        command: patroni /postgres0.yml
        volumes:
            - pg-master:/var/lib/postgresql/data

    pg-slave:
        build: 'postgres'
        container_name: pg-slave
        restart: always
        hostname: pg-slave
        expose:
            - 5432
            - 8008
        ports:
            - 5434:5432
        environment:
            POSTGRES_USER: alfresco
            POSTGRES_PASSWORD: alfresco
            POSTGRES_DB: alfresco
            PGDATA: '/var/lib/postgresql/data/pgdata'        
        command: patroni /postgres1.yml
        volumes:
            - pg-slave:/var/lib/postgresql/data
  
volumes:
    pg-master:
    pg-slave: