services:
    alfresco:
        image: docker.io/alfresco/alfresco-content-repository-community:23.4.0
        mem_limit: 1900m
        environment:
            JAVA_TOOL_OPTIONS: >-
                -Dencryption.keystore.type=JCEKS
                -Dencryption.cipherAlgorithm=DESede/CBC/PKCS5Padding
                -Dencryption.keyAlgorithm=DESede
                -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
                -Dmetadata-keystore.password=mp6yc0UD9e
                -Dmetadata-keystore.aliases=metadata
                -Dmetadata-keystore.metadata.password=oKIWzVdEdA
                -Dmetadata-keystore.metadata.algorithm=DESede
            JAVA_OPTS: >-
                -Ddb.driver=org.postgresql.Driver
                -Ddb.username=alfresco
                -Ddb.password=alfresco
                -Ddb.url=jdbc:postgresql://${IP_SERVER}:5433/alfresco
                -Dsolr.host=noindex
                -Dshare.host=localhost
                -Dshare.port=8080
                -Dalfresco.host=localhost
                -Dalfresco.port=8080
                -Daos.baseUrlOverwrite=http://localhost:8080/alfresco/aos
                -Dmessaging.broker.url="failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true"
                -Ddeployment.method=DOCKER_COMPOSE
                -Dtransform.service.enabled=false
                -Dlocal.transform.service.enabled=false
                -Dlegacy.transform.service.enabled=false
                -Dcsrf.filter.enabled=false
                -XX:MinRAMPercentage=50
                -XX:MaxRAMPercentage=80
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/alfresco/api/-default-/public/alfresco/versions/1/probes/-ready-"]
            interval: 30s
            timeout: 3s
            retries: 5
            start_period: 1m
        ports:
            - 9080:8080
        volumes:
            - ../alfresco/alfresco_data:/usr/local/tomcat/alf_data

    share:
        image: docker.io/alfresco/alfresco-share:23.4.0
        mem_limit: 1g
        environment:
            CSRF_FILTER_ORIGIN: http://localhost:8080
            CSRF_FILTER_REFERER: http://localhost:8080/share/.*
            REPO_HOST: "alfresco"
            REPO_PORT: "8080"
            JAVA_OPTS: >-
                -XX:MinRAMPercentage=50
                -XX:MaxRAMPercentage=80
                -Dalfresco.host=localhost
                -Dalfresco.port=8080
                -Dalfresco.context=alfresco
                -Dalfresco.protocol=http
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/share"]
            interval: 20s
            timeout: 2s
            retries: 3
            start_period: 15s
        depends_on:
            alfresco:
                condition: service_healthy
        ports:
            - 9081:8080
    
    activemq:
        image: alfresco/alfresco-activemq:5.18-jre17-rockylinux8
        mem_limit: 1g
        healthcheck:
            test: ["CMD", "/opt/activemq/bin/activemq", "query", "--objname", "type=Broker,brokerName=*,service=Health", "|", "grep", "Good"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 5s
